### ISSUE TITLE
New challenge

### ISSUE THREAD

**Issue by Tiaonmmn** [CTFTraining/CTFTraining#1]
Insomni hacker's teaser 2019 just finished.
Here's one challenge:https://github.com/Tiaonmmn/InsomniTeaser_2019_l33t-hoster

**Comment by virink** [comment]
There are some minor problems, but don't matter!
Next time, use `_` and **lowercase** in challenge name, plz!
```
- InsomniTeaser_2019_l33t-hoster
+ insomnteaser_2019_l33t_hoster
```

Thank you for your contribution.
