### ISSUE TITLE
New Challenge <delta_ctf_2019_web1_ssrf>

### ISSUE THREAD

**Issue by gwyxjtu** [CTFTraining/CTFTraining#23]
## New Challenge \<Challenge Name\>

- [x] I'm sure this challenge can be working.
- [ ] I got the right for the challenge or source code.
- [x] I used the open source code of others correctly.
- [x] I have strictly according to the contribution rules.
- [ ] I have not yet obtained the authorization, but I will delete this if the owner would not agree to use it. And I explained this in README.md.

## Code repository

<https://github.com/gwyxjtu/delta_ctf_2019_web1_ssrf>

**Comment by virink** [comment]
thx
