### ISSUE TITLE
New Challenge <Web_Unknow>

### ISSUE THREAD

**Issue by CoColizdf** [CTFTraining/CTFTraining#24]
## New Challenge \<Challenge Name\>

- [x ] I'm sure this challenge can be working.
- [x ] I got the right for the challenge or source code.
- [x ] I used the open source code of others correctly.
- [x ] I have strictly according to the contribution rules.
- [x ] I have not yet obtained the authorization, but I will delete this if the owner would not agree to use it. And I explained this in README.md.

## Code repository

https://github.com/CoColizdf/CTFTraining_Web_Unknow

**Comment by glzjin** [comment]
Please modify your Dockerfile to let Your image extend from the base image instead of directly fork it.
