### ISSUE TITLE
New Challenge <suctf_2019_upload_labs_2>

### ISSUE THREAD

**Issue by TomsSawyer** [CTFTraining/CTFTraining#42]
## New Challenge \<suctf_2019_upload_labs_2\>

- [x] I'm sure this challenge can be working.
- [x] I got the right for the challenge or source code.
- [x] I used the open source code of others correctly.
- [x] I have strictly according to the contribution rules.
- [x] I have not yet obtained the authorization, but I will delete this if the owner would not agree to use it. And I explained this in README.md.

## Code repository

\<https://github.com/TomsSawyer/suctf_2019_upload_labs_2 \>

**Comment by glzjin** [comment]
谢谢，之后请注意 docker-compose.yml 的书写，需要带上 image。
