### ISSUE TITLE
zjctf_2019_final_web_nizhuansiwei

### ISSUE THREAD

**Issue by fjh1997** [CTFTraining/CTFTraining#43]
## New Challenge \<Challenge Name\>

- [x] I'm sure this challenge can be working.
- [ ] I got the right for the challenge or source code.
- [x] I used the open source code of others correctly.
- [x] I have strictly according to the contribution rules.
- [x] I have not yet obtained the authorization, but I will delete this if the owner would not agree to use it. And I explained this in README.md.

## Code repository

\< https://github.com/fjh1997/zjctf_2019_final_web_nizhuansiwei \>

**Comment by glzjin** [comment]
Thanks.
