### ISSUE TITLE
强网杯 2019 copperstudy

### ISSUE THREAD

**Issue by 851579181** [CTFTraining/CTFTraining#9]
## New Challenge \<Challenge Name\>

- [x] I'm sure this challenge can be working.
- [x] I got the right for the challenge or source code.
- [x] I used the open source code of others correctly.
- [x] I have strictly according to the contribution rules.
- [x] I have not yet obtained the authorization, but I will delete this if the owner would not agree to use it. And I explained this in README.md.

## Code repository

https://github.com/851579181/qiangwangbei_2019_crypto_copperstudy

**Comment by virink** [comment]
Thank you for your efforts!!!
Hope you make others better~
